package aor.paj.projetofinalbackend.utils;

import org.mindrot.jbcrypt.BCrypt;

/**
 * Utility class for encrypting passwords using BCrypt hashing algorithm.
 *
 * @author João Morais
 * @author Ricardo Elias
 */
public class EncryptHelper {

    /**
     * Encrypts a plain text password using BCrypt hashing.
     *
     * @param plainPassword The plain text password to encrypt.
     * @return The hashed password generated by BCrypt.
     */
    public static String encryptPassword(String plainPassword) {
        return BCrypt.hashpw(plainPassword, BCrypt.gensalt());
    }

    /**
     * Checks if a plain text password matches the hashed password using BCrypt.
     *
     * @param plainPassword The plain text password to check.
     * @param hashedPassword The hashed password stored in the database.
     * @return True if the plain text password matches the hashed password, false otherwise.
     */
    public static boolean checkPassword(String plainPassword, String hashedPassword) {
        return BCrypt.checkpw(plainPassword, hashedPassword);
    }
}

